# Generated by Django 4.1.2 on 2022-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=60)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=60)),
                ('email_name', models.EmailField(help_text='Enter email', max_length=254)),
            ],
        ),
    ]
