# Generated by Django 4.1.2 on 2022-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('get_data', models.JSONField()),
                ('post_data', models.JSONField()),
                ('method', models.CharField(choices=[('g', 'GET'), ('p', 'POST'), ('h', 'HEAD'), ('u', 'PUT'), ('d', 'DELETE'), ('c', 'CONNECT'), ('o', 'OPTIONS'), ('t', 'TRACE'), ('a', 'PATCH')], default='g', help_text='request_method', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
