# Generated by Django 4.1.2 on 2022-10-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_name',
            new_name='email',
        ),
    ]
