# Generated by Django 4.1.2 on 2022-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='method',
            field=models.CharField(choices=[('ge', 'GET'), ('po', 'POST'), ('he', 'HEAD'), ('pu', 'PUT'), ('de', 'DELETE'), ('co', 'CONNECT'), ('op', 'OPTIONS'), ('tr', 'TRACE'), ('pa', 'PATCH')], default='g', help_text='request_method', max_length=2),
        ),
    ]
