# Generated by Django 4.1.2 on 2022-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_logs_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
